-- Static map coordinate support for VSM tactical image map.
ALTER TABLE "DispatchCall"
  ADD COLUMN "mapX" DOUBLE PRECISION,
  ADD COLUMN "mapY" DOUBLE PRECISION;

ALTER TABLE "MapPOI"
  ADD COLUMN "mapX" DOUBLE PRECISION,
  ADD COLUMN "mapY" DOUBLE PRECISION;

ALTER TABLE "MapPOI"
  ALTER COLUMN "lat" DROP NOT NULL,
  ALTER COLUMN "lng" DROP NOT NULL;
